name: Build from source

on:
  push:
    branches:
      - master
      - minidisc-ffwd
    tags:
      - '**'
  pull_request:
    branches:
      - master
      - minidisc-ffwd

jobs:
  build:
    runs-on: ${{ matrix.build_host }}
    strategy:
      fail-fast: false
      matrix:
        build_host:
          - ubuntu-latest
        build_type:
          - linux
          - mingw32
          - mingw64
        include:
           - build_host: macos-latest
             build_type: macos
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - run: git fetch --prune --tags
      - name: Install dependencies
        run: sh scripts/install_dependencies.sh
      - name: Configure, make, package
        run: sh scripts/configure_make_package.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-result
          path: dist/*
          if-no-files-found: ignore
      - name: Upload release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gh release create "${GITHUB_REF#refs/tags/}" || true
          gh release upload "${GITHUB_REF#refs/tags/}" dist/* || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
